import type { Digest, NewsItem, Source, ToolItem } from "./types";

export const sources: Source[] = [
  {
    id: "openai",
    name: "OpenAI News",
    url: "https://openai.com/news/",
    tier: "primary",
    topic: "AI obecne",
    cadence: "frequent",
    trustScore: 96,
    status: "active",
  },
  {
    id: "anthropic",
    name: "Anthropic Newsroom",
    url: "https://www.anthropic.com/news",
    tier: "primary",
    topic: "AI obecne",
    cadence: "frequent",
    trustScore: 95,
    status: "active",
  },
  {
    id: "deepmind",
    name: "Google DeepMind",
    url: "https://deepmind.google/blog/",
    tier: "primary",
    topic: "Vyzkum",
    cadence: "weekly",
    trustScore: 95,
    status: "active",
  },
  {
    id: "fda-ai-devices",
    name: "FDA AI-enabled Medical Devices",
    url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-aiml-enabled-medical-devices",
    tier: "sector",
    topic: "Medicina",
    cadence: "periodic",
    trustScore: 98,
    status: "active",
  },
  {
    id: "nejm-ai",
    name: "NEJM AI",
    url: "https://ai.nejm.org/",
    tier: "sector",
    topic: "Medicina",
    cadence: "monthly",
    trustScore: 94,
    status: "active",
  },
  {
    id: "bair",
    name: "BAIR Blog",
    url: "https://bair.berkeley.edu/blog/",
    tier: "research",
    topic: "Vyzkum",
    cadence: "biweekly",
    trustScore: 91,
    status: "active",
  },
  {
    id: "simon-willison",
    name: "Simon Willison",
    url: "https://simonwillison.net/",
    tier: "expert",
    topic: "Nastroje",
    cadence: "frequent",
    trustScore: 88,
    status: "active",
  },
  {
    id: "raschka",
    name: "Ahead of AI",
    url: "https://magazine.sebastianraschka.com/",
    tier: "expert",
    topic: "Vyzkum",
    cadence: "weekly",
    trustScore: 88,
    status: "active",
  },
  {
    id: "educause",
    name: "EDUCAUSE Review",
    url: "https://er.educause.edu/",
    tier: "sector",
    topic: "Vzdelavani",
    cadence: "weekly",
    trustScore: 84,
    status: "active",
  },
  {
    id: "latent-space",
    name: "Latent Space",
    url: "https://www.latent.space/",
    tier: "expert",
    topic: "AI obecne",
    cadence: "weekly",
    trustScore: 82,
    status: "review",
  },
];

export const newsItems: NewsItem[] = [
  {
    id: "clinical-ai-governance",
    title: "Klinicka AI se posouva od pilotu k rutinnim pracovnim postupum",
    source: "Stanford Medicine",
    sourceUrl: "https://medicine.stanford.edu/",
    publishedAt: "2026-04-28",
    topic: "Medicina",
    score: 94,
    summary:
      "Zdravotnicke systemy zrychluji nasazovani AI pro dokumentaci, triage, zobrazovani a vyhledavani medicinskych dukazu. Klicove tema uz neni pouze presnost modelu, ale governance, odpovednost a real-world evaluace.",
    whyItMatters:
      "Pro klinickou praxi bude rozhodujici, kdo AI validuje, jak se meri prinos a kde zustava lekar v rozhodovacim retezci.",
    tags: ["clinical AI", "governance", "evaluation"],
    readTime: "4 min",
  },
  {
    id: "agents-evals",
    title: "Agentni systemy potrebuji vlastni evaluace, ne jen benchmarky modelu",
    source: "LangChain Blog",
    sourceUrl: "https://www.langchain.com/blog",
    publishedAt: "2026-04-27",
    topic: "Nastroje",
    score: 89,
    summary:
      "Vyvojari produkcnich agentu se presouvaji od jednorazoveho promptovani k testovacim sadam, trace analyzam a prubeznemu hodnoceni schopnosti agentu v realnych procesech.",
    whyItMatters:
      "Pro Signalmind je to vzor pro vlastni hodnoceni kvality shrnuti, deduplikace a relevance zdroju.",
    tags: ["agents", "evals", "production"],
    readTime: "6 min",
  },
  {
    id: "ai-education-governance",
    title: "Skoly resi bring-your-own-AI a pravidla pro odpovedne pouzivani",
    source: "EDUCAUSE Review",
    sourceUrl: "https://er.educause.edu/",
    publishedAt: "2026-04-26",
    topic: "Vzdelavani",
    score: 84,
    summary:
      "Instituce posouvaji AI kompetence z IT oddeleni do rukou ucitelu, studentu a administrativy. Hlavnimi tematy jsou skoleni, soukromi dat, hodnoceni vystupu a nakup nastroju.",
    whyItMatters:
      "Vzdelavani nebude potrebovat jen seznam nastroju, ale system pro posuzovani, zda dany nastroj odpovida pedagogickemu cilu.",
    tags: ["education", "policy", "BYOAI"],
    readTime: "5 min",
  },
  {
    id: "frontier-time-horizon",
    title: "Schopnost modelu resit delsi ulohy se stava hlavni metrikou pokroku",
    source: "METR",
    sourceUrl: "https://metr.org/",
    publishedAt: "2026-04-25",
    topic: "Vyzkum",
    score: 91,
    summary:
      "Evaluace dlouhych autonomnich uloh ukazuji, ze prakticka schopnost AI agentu se neda vystihnout jednim skore v testu. Dulezite je, jak dlouhy a rozvetveny ukol model zvladne bez dohledu.",
    whyItMatters:
      "Signalizuje posun od chatovacich modelu k pracovnim systemum, ktere bude treba sledovat v medicinske administraci, vyuce i vyzkumu.",
    tags: ["frontier AI", "agents", "benchmarks"],
    readTime: "7 min",
  },
];

export const tools: ToolItem[] = [
  {
    id: "perplexity",
    name: "Perplexity",
    url: "https://www.perplexity.ai/",
    category: "Research assistant",
    pricing: "Freemium",
    summary: "AI vyhledavani se zdroji a rychlym syntetickym odpovidanim.",
    useCase: "Rychla orientace v tematu pred hlubsim ctenim primarnich zdroju.",
    signal: 82,
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    url: "https://notebooklm.google/",
    category: "Knowledge workspace",
    pricing: "Freemium",
    summary: "Prace s vlastnimi dokumenty, shrnuti, otazky a audio prehledy.",
    useCase: "Analyza dlouhych reportu, prednaskovych materialu a guideline dokumentu.",
    signal: 78,
  },
  {
    id: "open-evidence",
    name: "OpenEvidence",
    url: "https://www.openevidence.com/",
    category: "Medical evidence",
    pricing: "Unknown",
    summary: "Vyhledavani medicinskych dukazu pro klinicke otazky.",
    useCase: "Rychle mapovani literatury a klinickych doporuceni pro lekare.",
    signal: 86,
  },
  {
    id: "langsmith",
    name: "LangSmith",
    url: "https://www.langchain.com/langsmith",
    category: "Agent observability",
    pricing: "Freemium",
    summary: "Tracing, evaluace a ladeni LLM aplikaci a agentu.",
    useCase: "Kontrola kvality automatizovaneho zpracovani novinek ve vlastnim systemu.",
    signal: 80,
  },
];

export const digests: Digest[] = [
  {
    id: "2026-04-28",
    date: "28. 4. 2026",
    title: "AI se presouva z ukazek do provozu",
    focus: "governance, agenti, klinicka validace",
    items: [
      "Medicina: hlavnim tematem je real-world evaluace a odpovednost za doporuceni.",
      "Vzdelavani: instituce resi pravidla pro BYOAI a pripravu ucitelu.",
      "Nastroje: agentni frameworky zacinaji stavet vlastni evaluacni vrstvy.",
      "Vyzkum: benchmarky se posouvaji k delsim autonomnim uloham.",
    ],
  },
  {
    id: "2026-04-27",
    date: "27. 4. 2026",
    title: "Vyssi signal u zdroju s primarnimi daty",
    focus: "FDA, arXiv, Stanford HAI, expertni blogy",
    items: [
      "Prioritizovat primarni zdroje pred medialnimi prepisy.",
      "U nastroju ukladat cenu, free tier a prakticky use-case.",
      "U kazde novinky drzet zdrojovy odkaz a duvod relevance.",
    ],
  },
];

export const topicStats = [
  { label: "Medicina", value: 18, accent: "bg-emerald-500" },
  { label: "Vzdelavani", value: 11, accent: "bg-amber-500" },
  { label: "Vyzkum", value: 24, accent: "bg-violet-500" },
  { label: "Nastroje", value: 16, accent: "bg-cyan-500" },
];
